@extends('auth.layout')
@section('title', 'Two Factor Authentication Verification')
@section('content')
<style>
    .verification_code_box{
        text-align: center;
        margin: 0 5px;
        padding: 0;
        border: 1px solid #ccc;
        border-radius: 3px;
        width: 30px !important;
        height: 30px !important;
        font-size: 20px;
        font-weight: 600;
        display: inline;
    }
    .container{
        margin-top: 100px;
    }
    .logo {
        width: 200px;
        height: 50px;
        margin: 0 auto;
        display: block;
    }

</style>
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    {{-- <h5 class="m-0 text-dark">Welcome !! {{ auth::user()->name }}</h5> --}}
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        {{-- <li class="breadcrumb-item"><a href="#">2FA</a></li> --}}
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Main content -->
    <section class="content">
       
        <div class="container text-center ">
            <div class="row text-center py-2">
                {{-- image --}}
                <img src="{{ asset('logo.png') }}" alt="" class="logo">
            </div>
            <div class="row text-center">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="card py-5" >
                        <div class="text-center">Login</div>
                        <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                           <p class="py-2"> Enter the 6-digit verification code generated by your authenticator app</p>
                            <form class="form-horizontal" action="{{ route('2faVerify') }}" method="POST">
                                {{ csrf_field() }}
                                <div class="form-group{{ $errors->has('one_time_password-code') ? ' has-error' : '' }}">
                                    <input id="one_time_password" name="one_time_password" class="form-control col-md-4"
                                        type="hidden" required />
                                    <div class="verification-code d-flex justify-content-between">
                                        <input id="digit1" name="digit1" class="form-control col-md-1 verification_code_box" type="text" maxlength="1" required />
                                        <input id="digit2" name="digit2" class="form-control col-md-1 verification_code_box" type="text" maxlength="1" required />
                                        <input id="digit3" name="digit3" class="form-control col-md-1 verification_code_box" type="text" maxlength="1" required />
                                        <input id="digit4" name="digit4" class="form-control col-md-1 verification_code_box" type="text" maxlength="1" required />
                                        <input id="digit5" name="digit5" class="form-control col-md-1 verification_code_box" type="text" maxlength="1" required />
                                        <input id="digit6" name="digit6" class="form-control col-md-1 verification_code_box" type="text" maxlength="1" required />
                                    </div>
                                </div>
                                <button class="btn btn-success" type="submit">Login to you account</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </section>

   
<script>
    $(document).ready(function () {
        $("#digit1").focus();
        $("#digit1, #digit2, #digit3, #digit4, #digit5, #digit6").keyup(function () {
            if (this.value.length == this.maxLength) {
                var $next = $(this).next('.verification_code_box');
                if ($next.length)
                    $(this).next('.verification_code_box').focus();
                else
                    $(this).blur();
            }
            // backspace
            else if (this.value.length == 0) {
                var $prev = $(this).prev('.verification_code_box');
                if ($prev.length)
                    $(this).prev('.verification_code_box').focus();
            }
        });
    // get all code to hidden field
        $("#digit1, #digit2, #digit3, #digit4, #digit5, #digit6").keyup(function () {
            var digit1 = $("#digit1").val();
            var digit2 = $("#digit2").val();
            var digit3 = $("#digit3").val();
            var digit4 = $("#digit4").val();
            var digit5 = $("#digit5").val();
            var digit6 = $("#digit6").val();
            var one_time_password = digit1 + digit2 + digit3 + digit4 + digit5 + digit6;
            $("#one_time_password").val(one_time_password);
        });
    });
</script>

   
@endsection
      



